In [ ]:
import requests
import pandas as pd

url = "https://berita-indo-api.vercel.app/v1/cnn-news"
response = requests.get(url)

data = response.json()
news_data = data['data']

df = pd.DataFrame(news_data)
df

,title,link,contentSnippet,isoDate,image
0,"Persib Masuk Pot 1 ACL 2, Terhindar Jepang Dit...",https://www.cnnindonesia.com/olahraga/20251226...,Persib Bandung masuk Pot 1 undian babak 16 bes...,2025-12-26T11:40:13.000Z,{'small': 'https://akcdn.detik.net.id/visual/2...
1,Kemlu Pulangkan 9 WNI Korban Penipuan Online d...,https://www.cnnindonesia.com/internasional/202...,Kemlu RI memulangkan sembilan WNI dari Kamboja...,2025-12-26T11:32:06.000Z,{'small': 'https://akcdn.detik.net.id/visual/2...
2,VIDEO: Pembatasan Kendaraan Sumbu Tiga di Tol ...,https://www.cnnindonesia.com/tv/20251226174142...,Meski pembatasan kendaraan sumbu tiga di jalan...,2025-12-26T11:30:42.000Z,{'small': 'https://akcdn.detik.net.id/visual/2...
3,Pemukim Ilegal Israel Serang Warga Tepi Barat ...,https://www.cnnindonesia.com/internasional/202...,"Dalam aksi sewenang-wenang tersebut, para peny...",2025-12-26T11:25:06.000Z,{'small': 'https://akcdn.detik.net.id/visual/2...
4,VIDEO: Peringatan 21 Tahun Bencana Tsunami Aceh,https://www.cnnindonesia.com/tv/20251226172537...,Warga di Aceh Barat menggelar ziarah ke kubura...,2025-12-26T11:15:45.000Z,{'small': 'https://akcdn.detik.net.id/visual/2...
...,...,...,...,...,...
95,Apakah Diskon Tarif Tol Masih Berlaku Hari Ini?,https://www.cnnindonesia.com/ekonomi/202512260...,Sejumlah ruas tol memberlakukan diskon tarif u...,2025-12-26T02:00:35.000Z,{'small': 'https://akcdn.detik.net.id/visual/2...
96,Ratusan Sinkhole Muncul di Ladang Pertanian Tu...,https://www.cnnindonesia.com/teknologi/2025122...,Ratusan sinkhole atau lubang raksasa muncul di...,2025-12-26T01:50:48.000Z,{'small': 'https://akcdn.detik.net.id/visual/2...
97,Amorim: Mainoo adalah Masa Depan Manchester Un...,https://www.cnnindonesia.com/olahraga/20251226...,Pelatih Manchester United Ruben Amorim menyebu...,2025-12-26T01:41:09.000Z,{'small': 'https://akcdn.detik.net.id/visual/2...
98,11 Oleh-Oleh Khas Semarang untuk Wisatawan Baw...,https://www.cnnindonesia.com/gaya-hidup/202512...,Berkunjung ke Semarang tentu kurang lengkap ta...,2025-12-26T01:30:11.000Z,{'small': 'https://akcdn.detik.net.id/visual/2...
99,Pengamat: Pengibaran Bendera GAM Langgar Hukum...,https://www.cnnindonesia.com/nasional/20251226...,Pengamat menilai aksi pengibaran bendera GAM d...,2025-12-26T01:29:26.000Z,{'small': 'https://akcdn.detik.net.id/visual/2...

In [ ]:
df = df[['title', 'link', 'contentSnippet', 'isoDate']]

df = df.rename(columns={
    'title': 'news_title',
    'link': 'news_link',
    'contentSnippet': 'news_summary',
    'isoDate': 'published_at'
})

In [ ]:
df = df.drop_duplicates(subset='news_link')

In [ ]:
df = df.dropna(subset=['news_title', 'news_summary'])

In [ ]:
df['news_title'] = df['news_title'].str.title()
df['news_summary'] = df['news_summary'].str.lower()

In [ ]:
df['title_length'] = df['news_title'].str.len()
df['word_count'] = df['news_summary'].str.split().str.len()

In [ ]:
df = df[df['word_count'] > 5]

In [ ]:
df

,news_title,news_link,news_summary,published_at,title_length,word_count
0,"Persib Masuk Pot 1 Acl 2, Terhindar Jepang Dit...",https://www.cnnindonesia.com/olahraga/20251226...,persib bandung masuk pot 1 undian babak 16 bes...,2025-12-26T11:40:13.000Z,57,21
1,Kemlu Pulangkan 9 Wni Korban Penipuan Online D...,https://www.cnnindonesia.com/internasional/202...,kemlu ri memulangkan sembilan wni dari kamboja...,2025-12-26T11:32:06.000Z,57,23
2,Video: Pembatasan Kendaraan Sumbu Tiga Di Tol ...,https://www.cnnindonesia.com/tv/20251226174142...,meski pembatasan kendaraan sumbu tiga di jalan...,2025-12-26T11:30:42.000Z,57,20
3,Pemukim Ilegal Israel Serang Warga Tepi Barat ...,https://www.cnnindonesia.com/internasional/202...,"dalam aksi sewenang-wenang tersebut, para peny...",2025-12-26T11:25:06.000Z,64,19
4,Video: Peringatan 21 Tahun Bencana Tsunami Aceh,https://www.cnnindonesia.com/tv/20251226172537...,warga di aceh barat menggelar ziarah ke kubura...,2025-12-26T11:15:45.000Z,47,19
...,...,...,...,...,...,...
95,Apakah Diskon Tarif Tol Masih Berlaku Hari Ini?,https://www.cnnindonesia.com/ekonomi/202512260...,sejumlah ruas tol memberlakukan diskon tarif u...,2025-12-26T02:00:35.000Z,47,19
96,Ratusan Sinkhole Muncul Di Ladang Pertanian Tu...,https://www.cnnindonesia.com/teknologi/2025122...,ratusan sinkhole atau lubang raksasa muncul di...,2025-12-26T01:50:48.000Z,66,18
97,Amorim: Mainoo Adalah Masa Depan Manchester Un...,https://www.cnnindonesia.com/olahraga/20251226...,pelatih manchester united ruben amorim menyebu...,2025-12-26T01:41:09.000Z,50,15
98,11 Oleh-Oleh Khas Semarang Untuk Wisatawan Baw...,https://www.cnnindonesia.com/gaya-hidup/202512...,berkunjung ke semarang tentu kurang lengkap ta...,2025-12-26T01:30:11.000Z,54,19
99,Pengamat: Pengibaran Bendera Gam Langgar Hukum...,https://www.cnnindonesia.com/nasional/20251226...,pengamat menilai aksi pengibaran bendera gam d...,2025-12-26T01:29:26.000Z,69,18

In [ ]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    user="postgres",
    password="kukang12",
    dbname="assigment",
    port=5432
)

cursor = conn.cursor()

cursor.execute("TRUNCATE TABLE stg_news")

insert_query = """
INSERT INTO stg_news
(news_link, news_title, news_summary, published_at, title_length, word_count)
VALUES (%s, %s, %s, %s, %s, %s)
"""

for _, row in df.iterrows():
    cursor.execute(insert_query, (
        row['news_link'],
        row['news_title'],
        row['news_summary'],
        row['published_at'],
        row['title_length'],
        row['word_count']
    ))

conn.commit()
cursor.close()
conn.close()

OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

In [ ]:
import logging

for handler in logging.root.handlers[:]:
    logging.root.removeHandler(handler)

logging.basicConfig(
    filename="etl_log.txt",
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

try:
    logging.info("ETL Job Started (CNN News)")
    logging.info(f"Extracted {len(df)+1} records from API CNN News")
    logging.info("Data cleansing complete")
    logging.info("Data transformation complete")
    logging.info(f"Loaded {len(df)} records into stg_news")

    logging.info("ETL Job Finished Successfully")

except Exception as e:
    logging.error(f"ETL Job Failed: {str(e)}")